import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = resolve(__dirname, '..', 'output', 'temple-of-zeus-content');

/**
 * Ensure a directory exists, creating it and parents if needed.
 */
function ensureDir(dirPath) {
  if (!existsSync(dirPath)) {
    mkdirSync(dirPath, { recursive: true });
  }
}

/**
 * Save markdown content to the proper category folder.
 *
 * @param {string} filename - The output filename (without extension)
 * @param {string} category - Category folder name e.g. "03-Gods"
 * @param {string} markdown - The markdown content to save
 * @returns {string} The full output path
 */
export function saveFile(filename, category, markdown) {
  const categoryDir = resolve(OUTPUT_DIR, category);
  ensureDir(categoryDir);

  const filePath = resolve(categoryDir, `${filename}.md`);
  writeFileSync(filePath, markdown, 'utf-8');
  return filePath;
}

/**
 * Generate and save a summary index.md at the root of the output.
 *
 * @param {Array<{ url: string, path: string, category: string, status: string }>} results
 */
export function saveIndex(results) {
  ensureDir(OUTPUT_DIR);

  const lines = [
    '# Temple of Zeus — Downloaded Content',
    '',
    `Retrieved from https://templeofzeus.org/`,
    `Date: ${new Date().toISOString().split('T')[0]}`,
    `Total pages: ${results.length}`,
    '',
    '## Categories',
    '',
  ];

  // Group by category
  const byCategory = {};
  for (const r of results) {
    if (!byCategory[r.category]) byCategory[r.category] = [];
    byCategory[r.category].push(r);
  }

  const categoryOrder = [
    '01-Main', '02-About', '03-Gods', '04-Doctrines', '05-Philosophy',
    '06-Zevism-Branches', '07-Afterlife', '08-Magick', '09-Squares',
    '10-Chakras-Meditations', '11-Enlightenment', '12-Personalities',
    '13-Family', '14-Coven', '15-Rites', '16-Ethics', '17-Virtues',
    '18-Liturgical-Terms', '19-Resources', '99-Uncategorized',
  ];

  for (const cat of categoryOrder) {
    const items = byCategory[cat];
    if (!items || items.length === 0) continue;

    const successful = items.filter((r) => r.status === 'ok').length;
    const failed = items.filter((r) => r.status === 'fail').length;
    const statusStr = failed > 0 ? ` (${failed} failed)` : '';

    lines.push(`### ${cat}`);
    lines.push('');
    lines.push(`**${items.length} pages — ${successful} succeeded${statusStr}**`);
    lines.push('');

    for (const item of items) {
      const filename = item.filename || item.path.replace(/^\//, '').replace(/\.php$/i, '').replace(/\//g, '-');
      const icon = item.status === 'ok' ? '✅' : item.status === 'fail' ? '❌' : '⬜';
      lines.push(`- ${icon} [${filename}](${cat}/${filename}.md) — [source](${item.url})`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by temple-of-zeus-scraper*');

  const indexPath = resolve(OUTPUT_DIR, 'index.md');
  writeFileSync(indexPath, lines.join('\n'), 'utf-8');
  return indexPath;
}
